#!/usr/bin/env python3
"""Regenerate AML fixtures by executing the pinned Python MathBrain directly.

Reference-only dependencies are those of harmonix/haiku. Product checks consume
the committed AML fixtures without Python. --check compares every generated byte.
"""
import argparse
import hashlib
import importlib.util
import json
import math
from pathlib import Path


def quoted(value):
    return json.dumps(value, ensure_ascii=False)


def vector(name, values):
    return [f"{name} = zeros({len(values)})"] + [
        f"{name}[{i}] = {v:.17g}" for i, v in enumerate(values)
    ]


def context(values):
    return ["user = list_new()"] + [
        f"list_push(user, {quoted(word)})" for triple in values for word in triple
    ]


class Capture:
    def __init__(self, model):
        self.model = model
        self.features = None
        self.raw = None

    def __call__(self, values):
        self.features = [v.data for v in values]
        prediction = self.model(values)
        self.raw = prediction.data
        return prediction

    def parameters(self):
        return self.model.parameters()


def analytic(parameters, x, target):
    """Independent scalar chain rule, in the source's parameter order."""
    hidden = []
    for j in range(8):
        activation = parameters[6 * j + 5]
        for k in range(5):
            activation += parameters[6 * j + k] * x[k]
        hidden.append(math.tanh(activation))
    activation = parameters[56]
    for j in range(8):
        activation += parameters[48 + j] * hidden[j]
    prediction = math.tanh(activation)
    delta = 2 * (prediction - target) * (1 - prediction * prediction)
    gradient = [0.0] * 57
    for j in range(8):
        dh = delta * parameters[48 + j] * (1 - hidden[j] * hidden[j])
        for k in range(5):
            gradient[j * 6 + k] = dh * x[k]
        gradient[j * 6 + 5] = dh
        gradient[48 + j] = delta * hidden[j]
    gradient[56] = delta
    return prediction, (prediction - target) ** 2, gradient


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--python-haiku", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    inputs = json.loads((root / "tests/reference/mathbrain_inputs.json").read_text())
    source = args.python_haiku / "haiku.py"
    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    assert digest == inputs["source_sha256"], "Unexpected Python haiku.py source"
    spec = importlib.util.spec_from_file_location("haiku_mathbrain_reference", source)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    def model(parameters=None, transitions=True, lr=0.01):
        instance = module.HaikuGenerator.__new__(module.HaikuGenerator)
        instance.mlp_scorer = Capture(module.MLP(5, [8, 1]))
        for parameter, value in zip(instance.mlp_scorer.parameters(),
                                    parameters or inputs["initial_parameters"]):
            parameter.data = value
        instance.markov_chain = {}
        if transitions:
            for a, b, c, n in inputs["transitions"]:
                instance.markov_chain.setdefault((a, b), {})[c] = n
        instance.lr = lr
        instance.observations = 0
        instance.last_loss = 0.0
        instance.running_loss = 0.0
        return instance

    def memory():
        lines = ["rows = list_new()", "counts = map_new()"]
        for a, b, c, n in inputs["transitions"]:
            lines += [f"list_push(rows, {quoted(w)})" for w in (a, b, c)]
            lines += [f"map_set(counts, list_key(list_slice(rows, list_len(rows) - 3, list_len(rows))), {n})"]
        return lines

    outputs = {}
    header = ['IMPORT "mathbrain_support.aml"']
    trailer = ["ECHO HAIKU_MATHBRAIN_OK"]
    lines = header + vector("parameters", inputs["initial_parameters"]) + memory()
    feature_values = 0
    for case in inputs["cases"]:
        instance = model()
        score = instance.score_haiku(case["text"], case["context"])
        lines += [f"# {case['name']}", f"source = {quoted(case['text'])}"] + context(case["context"])
        if instance.mlp_scorer.features is not None:
            lines += vector("expected", instance.mlp_scorer.features)
            lines += ["mathbrain_vector(haiku_mathbrain_features(source, rows, counts, user), expected)"]
            feature_values += 5
        lines += [f"mathbrain_check(haiku_mathbrain_score(parameters, source, rows, counts, user), {score:.17g})"]
        feature_values += 1
    outputs["mathbrain_features.aml"] = [f"# Numeric reference values: {feature_values}"] + lines + trailer

    instance = model()
    worst_gradient = 0.0
    for group in range(inputs["steps"] // 4):
        lines = header + vector("parameters", [p.data for p in instance.mlp_scorer.parameters()]) + memory()
        lines += ["state = haiku_mathbrain_state()",
                  f'map_set(state, "observations", {instance.observations})',
                  f'map_set(state, "last_loss", {instance.last_loss:.17g})',
                  f'map_set(state, "running_loss", {instance.running_loss:.17g})']
        for offset in range(4):
            index = group * 4 + offset
            case = inputs["cases"][index % 8]
            quality = inputs["qualities"][index % len(inputs["qualities"])]
            before = [p.data for p in instance.mlp_scorer.parameters()]
            loss = instance.observe(case["text"], quality, case["context"])
            gradients = [p.grad for p in instance.mlp_scorer.parameters()]
            raw, expected_loss, expected_gradient = analytic(
                before, instance.mlp_scorer.features, max(0, min(1, quality)))
            assert abs(raw - instance.mlp_scorer.raw) <= 1e-14
            assert abs(loss - expected_loss) <= 1e-14
            error = max(abs(a - b) for a, b in zip(gradients, expected_gradient))
            worst_gradient = max(worst_gradient, error)
            assert error <= 1e-14
            lines += [f"# Step {index + 1}: {case['name']}", f"source = {quoted(case['text'])}"] + context(case["context"])
            lines += ["features = haiku_mathbrain_features(source, rows, counts, user)"]
            lines += vector("expected", instance.mlp_scorer.features)
            lines += ["mathbrain_vector(features, expected)"]
            lines += vector("expected", [instance.mlp_scorer.raw, loss] + gradients)
            lines += [f"mathbrain_vector(haiku_learner_gradient(parameters, features, 5, 8, {max(0, min(1, quality)):.17g}), expected)"]
            lines += [f"loss = haiku_mathbrain_observe(parameters, state, source, {quality:.17g}, rows, counts, user)",
                      f"mathbrain_check(loss, {loss:.17g})"]
            lines += vector("expected", [p.data for p in instance.mlp_scorer.parameters()])
            lines += ["mathbrain_vector(parameters, expected)",
                      f'mathbrain_check(map_get(state, "observations"), {instance.observations})',
                      f'mathbrain_check(map_get(state, "last_loss"), {instance.last_loss:.17g})',
                      f'mathbrain_check(map_get(state, "running_loss"), {instance.running_loss:.17g})']
        outputs[f"mathbrain_steps_{group + 1}.aml"] = ["# Numeric reference values: 500"] + lines + trailer

    for index, case in enumerate(inputs["boundary_cases"]):
        instance = model(case["parameters_before"], transitions=False, lr=case["lr"])
        score = instance.score_haiku("one two three")
        loss = instance.observe("one two three", case["quality"])
        lines = header + vector("parameters", case["parameters_before"])
        lines += ["rows = list_new()", "counts = map_new()", "user = list_new()",
                  "state = haiku_mathbrain_state()", f'map_set(state, "lr", {case["lr"]:.17g})',
                  'source = "one two three"',
                  f"mathbrain_check(haiku_mathbrain_score(parameters, source, rows, counts, user), {score:.17g})",
                  "features = haiku_mathbrain_features(source, rows, counts, user)"]
        lines += vector("expected", [instance.mlp_scorer.raw, loss] + [p.grad for p in instance.mlp_scorer.parameters()])
        lines += [f"mathbrain_vector(haiku_learner_gradient(parameters, features, 5, 8, {case['quality']:.17g}), expected)",
                  f"loss = haiku_mathbrain_observe(parameters, state, source, {case['quality']:.17g}, rows, counts, user)",
                  f"mathbrain_check(loss, {loss:.17g})"]
        lines += vector("expected", [p.data for p in instance.mlp_scorer.parameters()])
        lines += ["mathbrain_vector(parameters, expected)",
                  f'mathbrain_check(map_get(state, "observations"), {instance.observations})',
                  f'mathbrain_check(map_get(state, "last_loss"), {instance.last_loss:.17g})',
                  f'mathbrain_check(map_get(state, "running_loss"), {instance.running_loss:.17g})']
        outputs[f"mathbrain_boundary_{index + 1}.aml"] = ["# Numeric reference values: 121", f"# {case['name']}"] + lines + trailer

    lines = header[:]
    generic_values = 0
    for nin, nhidden, x, target in [(1, 1, [-0.75], -0.6),
                                   (2, 3, [0.25, -0.8], 0.3),
                                   (5, 1, [-1, 0.5, 0.25, 0, 1], -0.2)]:
        network = module.MLP(nin, [nhidden, 1])
        parameters = [((i * 7 + 3) % 17 - 8) / 32 for i in range(len(network.parameters()))]
        for parameter, value in zip(network.parameters(), parameters):
            parameter.data = value
        prediction = network([module.Value(value) for value in x])
        loss = (prediction - module.Value(target)) ** 2
        loss.backward()
        lines += vector("parameters", parameters) + vector("features", x)
        lines += vector("expected", [prediction.data, loss.data] + [p.grad for p in network.parameters()])
        lines += [f"mathbrain_vector(haiku_learner_gradient(parameters, features, {nin}, {nhidden}, {target}), expected)"]
        lines += vector("expected", [prediction.data, loss.data] + [p.data - 0.01 * p.grad for p in network.parameters()])
        lines += [f"mathbrain_vector(haiku_learner_step(parameters, features, {nin}, {nhidden}, {target}, 0.01), expected)"]
        generic_values += 2 * (len(parameters) + 2)
    outputs["mathbrain_generic.aml"] = [f"# Numeric reference values: {generic_values}"] + lines + trailer

    for name, lines in outputs.items():
        text = "\n".join(lines) + "\n"
        assert max(len(line.encode()) for line in lines) < 256
        assert len(lines) < 1000
        path = root / "tests/fixtures" / name
        if args.check:
            assert path.read_text() == text, f"Fixture differs: {path}"
        else:
            path.write_text(text)
    print(f"MathBrain: {feature_values + 24 * 125 + 5 * 121 + generic_values} reference values; "
          f"24 complete steps; analytic gradient error {worst_gradient:.3g}")


if __name__ == "__main__":
    main()
